; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s15 cTeal, Consolas
Gui Add, Text, x8 y8 w317 h23 +0x200 +Center   , Cso StudioTool v0.3.04
Gui Font
Gui Add, Text, x-8 y40 w2 h332 +0x1 +0x10      
Gui Font, s10, Segoe Print
Gui Add, Text, x208 y472 w125 h20 +0x200 +Right   , By FeiMi. v0.3.05
Gui Font
Gui Add, GroupBox, x8 y48 w161 h119, 建造輔助
Gui Add, CheckBox, x16 y64 w118 h23 +Disabled   , F3 左鍵不放
Gui Add, CheckBox, x16 y88 w120 h23 +Disabled    , F4 自動 建造/破壞
Gui Add, GroupBox, x176 y48 w159 h124, 自動 建造/破壞
Gui Add, Text, x184 y64 w31 h23 +0x200 +Center    , 長度
Gui Add, Text, x184 y88 w31 h23 +0x200 +Center    , 寬度
Gui Add, GroupBox, x8 y416 w327 h46, 自動蓋Pixel畫
Gui Add, Text, x184 y112 w31 h23 +0x200 +Center    , 高度
Gui Add, Text, x184 y136 w31 h23 +0x200 +Center    , 槍種
Gui Add, ComboBox, x224 y136 w88, 建造步槍
Gui Add, CheckBox, x16 y192 w145 h23, F5 快速 V+6
Gui Add, CheckBox, x16 y264 w144 h23 +Disabled    , F`% 一鍵放置 訊息方塊
Gui Add, CheckBox, x16 y216 w144 h23 +Disabled   , F`% 一鍵放置 CV-47
Gui Add, CheckBox, x16 y240 w144 h23 +Disabled    , F`% 一鍵放置 100`%血包
Gui Add, Button, x256 y432 w67 h22 -Theme, &載入圖片
Gui Add, Text, x8 y472 w140 h23 +0x200 +Center    , [Esc] 關閉應用程式
Gui Add, GroupBox, x8 y176 w163 h144, 小朋友出征 :>
Gui Add, CheckBox, x184 y192 w144 h23 +Disabled   , F`% 一鍵存檔
Gui Add, Edit, x224 y64 w86 h21
Gui Add, Edit, x224 y88 w86 h21
Gui Add, Edit, x224 y112 w86 h21
Gui Add, Text, x9 y38 w313 h2 +0x10
Gui Add, CheckBox, x184 y216 w144 h23 +Disabled   , F`% 一鍵空氣牆
Gui Add, GroupBox, x176 y176 w158 h144, 特殊功能
Gui Add, GroupBox, x8 y320 w326 h92, 娛樂輔助
Gui Add, CheckBox, x16 y336 w144 h23 +Disabled    , F`% 一鍵射擊 音效

Gui Show, w343 h503, Cso StudioTool v0.3.04
Return


; Function 
Function_V6(status){
    if (status = "on") {
        while TRUE {
            Send, 
            Sleep % 80
        }
    }
}
Mouse_m1(status){
    if (status = "on") {
        while TRUE {
            Send, {LButton}
            Sleep % 150
        }
    }
}
; ---------------
; ---------------


; HotKey
F4::
Reload
Function_V6(status:="off")
TrayTip,,% "Stop"
Return

F5::Function_V6(status:="on")

F6::Mouse_m1(status:="on")

; ---------------
; ---------------
;v0.305

GuiEscape:
GuiClose:
    ExitApp
